name: Setup frontend environment
description: Setup frontend environment

inputs:
  node-version:
    description: node version
    default: "18"
    required: false
  yarn-version:
    description: yarn version
    default: "3.6.4"
    required: false
  directory:
    description: frontend directory
    default: "web"
    required: false

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node-version }}"

    - name: Set Yarn version
      shell: bash
      run: |
        corepack enable
        corepack prepare yarn@${{ inputs.yarn-version }} --activate
        corepack yarn --version
        which yarn
        ls -l $(which yarn)

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=${{ inputs.directory }}/.yarn/cache" >> $GITHUB_OUTPUT

    - name: Configure yarn cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install yarn dependencies
      working-directory: "${{ inputs.directory }}"
      shell: bash
      run: yarn install --immutable

    - name: Print Yarn cache size
      shell: bash
      run: du -d 0 -h ${{ steps.yarn-cache-dir-path.outputs.dir }}

    - name: Debug Yarn version
      shell: bash
      run: yarn --version

    - name: Debug PATH and corepack
      shell: bash
      run: |
        echo $PATH
        which yarn
        corepack --version
