name: Setup frontend environment
description: Setup frontend environment with optimized caching

inputs:
  node-version:
    description: node version
    default: "22"
    required: false
  directory:
    description: frontend directory
    default: "web"
    required: false

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node-version }}"
        cache: 'yarn'
        cache-dependency-path: "${{ inputs.directory }}/yarn.lock"

    # we use the exact restore key to avoid Cypress binary snowballing
    # https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/
    - name: Cache Cypress binary
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install yarn dependencies
      working-directory: "${{ inputs.directory }}"
      shell: 'bash'
      run: |
        yarn install --frozen-lockfile --prefer-offline --network-timeout 300000