# Generated by Django 4.2.16 on 2024-01-15 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import label_studio.fsm.utils


class Migration(migrations.Migration):
    """
    Initial migration for core FSM functionality in Label Studio.
    
    Creates the base state tracking infrastructure with UUID7 optimization
    for high-performance time-series data.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0055_task_proj_octlen_idx_async'),  # Latest task migration
        ('projects', '0030_project_search_vector_index'),  # Latest project migration
    ]

    operations = [
        migrations.CreateModel(
            name='TaskState',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=label_studio.fsm.utils.generate_uuid7,
                        editable=False,
                        help_text='UUID7 provides natural time ordering and global uniqueness',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('state', models.CharField(
                    choices=[
                        ('CREATED', 'Created'), 
                        ('IN_PROGRESS', 'In Progress'), 
                        ('COMPLETED', 'Completed')
                    ],
                    db_index=True, 
                    help_text='Current state of the entity', 
                    max_length=50
                )),
                (
                    'previous_state',
                    models.CharField(
                        blank=True,
                        help_text='Previous state before this transition',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'transition_name',
                    models.CharField(
                        blank=True,
                        help_text='Name of the transition method that triggered this state change',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'context_data',
                    models.JSONField(
                        default=dict,
                        help_text='Additional context data for this transition (e.g., validation results, external IDs)',
                    ),
                ),
                (
                    'reason',
                    models.TextField(
                        blank=True, help_text='Human-readable reason for this state transition'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=False,
                        help_text='Human-readable timestamp for debugging (UUID7 id contains precise timestamp)',
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fsm_states',
                        to='tasks.task',
                    ),
                ),
                (
                    'triggered_by',
                    models.ForeignKey(
                        help_text='User who triggered this state transition',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'fsm_task_states',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=label_studio.fsm.utils.generate_uuid7,
                        editable=False,
                        help_text='UUID7 provides natural time ordering and global uniqueness',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('state', models.CharField(
                    choices=[
                        ('CREATED', 'Created'), 
                        ('PUBLISHED', 'Published'), 
                        ('IN_PROGRESS', 'In Progress'), 
                        ('COMPLETED', 'Completed')
                    ],
                    db_index=True, 
                    help_text='Current state of the entity', 
                    max_length=50
                )),
                (
                    'previous_state',
                    models.CharField(
                        blank=True,
                        help_text='Previous state before this transition',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'transition_name',
                    models.CharField(
                        blank=True,
                        help_text='Name of the transition method that triggered this state change',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'context_data',
                    models.JSONField(
                        default=dict,
                        help_text='Additional context data for this transition (e.g., validation results, external IDs)',
                    ),
                ),
                (
                    'reason',
                    models.TextField(
                        blank=True, help_text='Human-readable reason for this state transition'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=False,
                        help_text='Human-readable timestamp for debugging (UUID7 id contains precise timestamp)',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fsm_states',
                        to='projects.project',
                    ),
                ),
                (
                    'triggered_by',
                    models.ForeignKey(
                        help_text='User who triggered this state transition',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'fsm_project_states',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='AnnotationState',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=label_studio.fsm.utils.generate_uuid7,
                        editable=False,
                        help_text='UUID7 provides natural time ordering and global uniqueness',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('state', models.CharField(
                    choices=[
                        ('DRAFT', 'Draft'), 
                        ('SUBMITTED', 'Submitted'), 
                        ('COMPLETED', 'Completed')
                    ],
                    db_index=True, 
                    help_text='Current state of the entity', 
                    max_length=50
                )),
                (
                    'previous_state',
                    models.CharField(
                        blank=True,
                        help_text='Previous state before this transition',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'transition_name',
                    models.CharField(
                        blank=True,
                        help_text='Name of the transition method that triggered this state change',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'context_data',
                    models.JSONField(
                        default=dict,
                        help_text='Additional context data for this transition (e.g., validation results, external IDs)',
                    ),
                ),
                (
                    'reason',
                    models.TextField(
                        blank=True, help_text='Human-readable reason for this state transition'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=False,
                        help_text='Human-readable timestamp for debugging (UUID7 id contains precise timestamp)',
                    ),
                ),
                (
                    'annotation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fsm_states',
                        to='tasks.annotation',
                    ),
                ),
                (
                    'triggered_by',
                    models.ForeignKey(
                        help_text='User who triggered this state transition',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'fsm_annotation_states',
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        # Create indexes for optimal performance with UUID7
        migrations.RunSQL(
            sql=[
                # Task state indexes - critical for current state lookups
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS fsm_task_current_state_idx ON fsm_task_states (task_id, id DESC);",
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS fsm_task_history_idx ON fsm_task_states (task_id, id);",
                
                # Annotation state indexes
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS fsm_anno_current_state_idx ON fsm_annotation_states (annotation_id, id DESC);",
                
                # Project state indexes
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS fsm_proj_current_state_idx ON fsm_project_states (project_id, id DESC);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS fsm_task_current_state_idx;",
                "DROP INDEX IF EXISTS fsm_task_history_idx;",
                "DROP INDEX IF EXISTS fsm_anno_current_state_idx;",
                "DROP INDEX IF EXISTS fsm_proj_current_state_idx;",
            ]
        ),
    ]