# Generated by Django 5.1.9 on 2025-06-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_userproducttour"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="custom_hotkeys",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
