name: Serve Frontend
description: Serve the built Label Studio Frontend using npx serve

inputs:
  directory:
    description: Directory containing the built frontend
    default: "web/dist/libs/editor"
    required: false
  port:
    description: Port to serve on
    default: "3000"
    required: false

outputs:
  pid:
    description: Process ID of the serve process
    value: ${{ steps.serve.outputs.pid }}

runs:
  using: composite
  steps:
    - name: Install serve
      shell: bash
      run: npm install -g serve

    - name: Start serve
      id: serve
      shell: bash
      run: |
        serve -s ${{ inputs.directory }} -l ${{ inputs.port }} &
        pid=$!
        echo "pid=${pid}" >> $GITHUB_OUTPUT

        # Wait for server to be ready
        while ! curl -s -o /dev/null -L "http://localhost:${{ inputs.port }}"; do
          echo "=> Waiting for service to become available"
          sleep 2s
        done 