name: "yarn integration"

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string

env:
  NODE: "22"
  FRONTEND_MONOREPO_DIR: "web"

jobs:
  main:
    name: "yarn integration"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Configure git
        shell: bash
        run: |
          set -xeuo pipefail
          git config --global user.name 'robot-ci-heartex'
          git config --global user.email 'robot-ci-heartex@users.noreply.github.com'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup frontend environment
        uses: ./.github/actions/setup-frontend-environment
        with:
          node-version: "${{ env.NODE }}"
          directory: "${{ env.FRONTEND_MONOREPO_DIR }}"

      - name: Run server
        id: run-server
        timeout-minutes: 2
        working-directory: ${{ env.FRONTEND_MONOREPO_DIR }}
        run: |
          set -xeuo pipefail
          
          yarn lsf:serve &
          pid=$!
          echo "pid=${pid}" >> $GITHUB_OUTPUT
          
          while ! curl -s -o /dev/null -L "http://localhost:3000"; do
            echo "=> Waiting for service to become available"
            sleep 2s
          done

      - name: Run integration tests
        working-directory: ${{ env.FRONTEND_MONOREPO_DIR }}
        env:
          COLLECT_COVERAGE: true
          CI: true
        run: |
          yarn test:integration:coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-coverage
          path: |
            web/coverage/
            web/libs/*/coverage/
          retention-days: 30

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-artifacts
          path: |
            web/dist/cypress/
            web/cypress-logs.*
          retention-days: 7

      - name: Kill server
        if: always()
        continue-on-error: true
        run: kill -9 "${{ steps.run-server.outputs.pid }}"
