name: "yarn unit"

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string

env:
  NODE: "22"
  FRONTEND_MONOREPO_DIR: "web"

jobs:
  main:
    name: "yarn unit"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Configure git
        shell: bash
        run: |
          set -xeuo pipefail
          git config --global user.name 'robot-ci-heartex'
          git config --global user.email 'robot-ci-heartex@users.noreply.github.com'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup frontend environment
        uses: ./.github/actions/setup-frontend-environment
        with:
          node-version: "${{ env.NODE }}"
          directory: "${{ env.FRONTEND_MONOREPO_DIR }}"

      - name: Run tests
        working-directory: ${{ env.FRONTEND_MONOREPO_DIR }}
        run: |
          yarn test:unit:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          name: unit-tests-coverage
          path: ${{ env.FRONTEND_MONOREPO_DIR }}/coverage/